FROM golang:1.24 AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-X main.build=${BUILD_REF}" -o /bin/scraper ./api/services/scraper/...

# =====================================================================================================================

FROM gcr.io/distroless/static-debian12
COPY --from=build /bin/scraper /bin/scraper
CMD ["/bin/scraper"]
