FROM golang:1.24 AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-X main.build=${BUILD_REF}" -o /bin/sheet ./api/services/sheet/...

# =====================================================================================================================

FROM gcr.io/distroless/static-debian12
COPY --from=build /bin/sheet /bin/sheet
CMD ["/bin/sheet"]
